### ISSUE TITLE
Bug: Click zone on color toggle rotating with icon effect

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#11591] opened 2023-11-06 08:54 UTC
### Describe the bug

Recently an animation was added to the color-mode icon in the nav bar, to rotate slightly on hover. Noticing that we're rotating the whole container, including the click zone, instead of just the icon.

We should also make sure to apply this same effect for `focus` state, not only `hover`

### To reproduce

1. Go to https://ethereum.org
2. Use keyboard to tab over to the moon/sun color-mode toggle icon
3. Hover over this element and notice that the whole click box rotate

### Expected behavior

Would expect the icon _only_ to rotate, not the containing box. Also, would expect same effect on keyboard focus. 

### Screenshots

<img width="434" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/3158a83f-cc58-475d-b5e9-aef1037713f2">

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by ATREAY** [comment] 2023-11-07 06:55
Hey @wackerow, can I work on this issue if it's available?

**Comment by wackerow** [comment] 2023-11-07 07:12
@ATREAY Hey, thanks for offering! We had a volunteer for this task via Discord already... let me check on that before assigning you

**Comment by ATREAY** [comment] 2023-11-07 09:23
Sure, @wackerow, if no one takes this issue, let me know. I'll look for another one in the meantime.

**Comment by rohan9024** [comment] 2023-11-07 14:44
> @ATREAY Hey, thanks for offering! We had a volunteer for this task via Discord already... let me check on that before assigning you

Hey @wackerow Assign me!

**Comment by wackerow** [comment] 2023-11-08 05:21
Thanks @rohan9024, just assigned you, let us know if you hit issues... apologies @ATREAY, can try to get you on another one!

**Comment by rohan9024** [comment] 2023-11-08 06:14
Thanks @wackerow

**Comment by tomasgrusz** [comment] 2024-06-13 14:16
Seems the issue is stale @wackerow . I'm happy to look into it if it's ready to be picked up again.

**Comment by wackerow** [comment] 2024-06-13 14:40
Thanks @tomasgrusz! Went ahead and assigned

**Comment by corwintines** [comment] 2024-07-03 01:01
Closing with the above PR

**Closed by corwintines** 2024-07-03 01:01 UTC
Labels: bug 🐛, help wanted, good first issue
