### ISSUE TITLE
UI Bug report: Update Twitter Logo

### ISSUE THREAD

**Issue by jenish-thapa** [ethereum/ethereum-org-website#13529] opened 2024-07-29 07:19 UTC
### Describe the bug

Request to update the Twitter logo used in our project. The current logo seems outdated and does not reflect Twitter's latest branding guidelines.

### To reproduce

1. Go to https://ethereum.org/en/
2. Scroll down to the bottom of the page
3. See error

### Expected behavior

- The Twitter logo in the project should be updated to the latest version provided by Twitter.
- The updated logo should be consistently displayed across all instances where the Twitter logo is used.

### Screenshots

![image](https://github.com/user-attachments/assets/76aab40d-ab3b-4bfe-9317-05c18ce07317)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by kohantikanath** [comment] 2024-07-29 07:22
Hi @jenish-thapa @wackerow @konopkja ,
I would love to work on this issue, can you assign me this issue?

**Comment by jay-691** [comment] 2024-08-01 17:38
here

**Comment by ankur-kalita** [comment] 2024-08-04 05:58
hey @jenish-thapa @jay-691 @chuyeow @kohantikanath I want to contribute to issue , could please assign it to me

**Comment by rohitt-gupta** [comment] 2024-08-04 08:33
@corwintines Added a PR for this.
Please review and merge

**Comment by ankur-kalita** [comment] 2024-08-04 09:15
@jenish-thapa raised a PR for this issue, please review it and merge the changes.

**Comment by TylerAPfledderer** [comment] 2024-08-04 18:50
@rohitt-gupta and @ankur-kalita for the future, please wait for a core member to address and assign the issue before pulling a PR. This has now resulted in duplicate PRs in the repo. 

We want to make sure duplicate PRs are prevented and not pile on to the existing PRs the team has to sort through.

cc @pettinarip @corwintines

**Comment by rohitt-gupta** [comment] 2024-08-04 18:55
I thought it was obvious that if a PR already raised, that means someone already fixed it and waiting for the review @ankur-kalita 
But never mind.

**Comment by wackerow** [comment] 2024-08-06 23:38
Okay, let's try to get organized here:

- #12379
Original issue about this, closed as of a few hours ago
- #13103
Closed as a duplicate of original issue
- #13515
PR fixing original issue, posted 2 weeks ago. Now merged, as of a few hours ago.
- #13529
Current issue; appears to be a duplicate again.
- #13573
Closed out in favor of the above. 

Going to close this one out now too. Cheers folks, the icon has been updated.

**Closed by wackerow** 2024-08-06 23:38 UTC
Labels: bug 🐛, needs triage 📥
