### ISSUE TITLE
Glossary Suggestion:  F.U.D. Fear, Uncertainty, and Doubt.

### ISSUE THREAD

**Issue by ThePrudentPatriot** [ethereum/ethereum-org-website#3152] opened 2021-05-28 02:12 UTC
F.U.D. Fear, Uncertainty, and Doubt. Often used to refer to negative, misleading, or false information relating to a cryptocurrency, token, or the wider industry.

An example of F.U.D. being used by a prominent member of Society, was Elon Musk. When he announced that Tesla would no longer accept Bitcoin as a form of payment, because it is not friendly to the environment. 

https://abcnews.go.com/Business/bitcoin-plunges-elon-musk-puts-environmental-impact-scrutiny/story?id=77665619

**Comment by ryancreatescopy** [comment] 2021-05-28 07:29
I'm not seeing anything we can look at or work on for ethereum.org in this issue. Closing out, feel free to reopen if you have a content/feature request or a bug to report.

**Comment by ThePrudentPatriot** [comment] 2021-05-28 07:39
Were these definitions not able to be used for the glossary?

**Comment by ryancreatescopy** [comment] 2021-05-28 08:01
My mistake, re-opening! Please let us know the intention of your issue in future

**Comment by ThePrudentPatriot** [comment] 2021-05-28 08:05
I'm very new to this. Can you exclaim a little bit what you mean?
Consolidate?

**Comment by ryancreatescopy** [comment] 2021-05-28 08:09
You currently have two issues open with two slightly different definitions. Pick which one you'd like to suggest and close the other issue. It's unclear to us what content you're suggesting right now.

**Comment by ThePrudentPatriot** [comment] 2021-05-28 08:11
I did make two glossary terms. How do I delete the one I do not like?

**Comment by ThePrudentPatriot** [comment] 2021-05-28 08:16
I deleted one of the FUD definitions. Sorry about that. Super new to this.
I just want to help. And grab one of those NFT POAP!

**Comment by ThePrudentPatriot** [comment] 2021-05-28 20:56
What do I do next? If you don't mind my asking?

**Comment by David-J-Mo** [comment] 2021-05-29 08:51
I think this should definitely be added to the glossary, but I think the definition might be a little long. Here's an alternative:

_Fear, uncertainty, and doubt. Often used to refer to negative, misleading, or false information relating to a cryptocurrency, token, or the wider industry._

**Comment by minimalsm** [comment] 2021-05-29 21:00
> Is the term/definition directly relevant to Ethereum?

If we include FUD do we include other trading terms? (Bull, bear, HODL, etc..)

**Comment by ThePrudentPatriot** [comment] 2021-05-30 22:18
I fixed it. I removed all the long text. Used your shorter text. Left the
example. If thats ok.

**Comment by ThePrudentPatriot** [comment] 2021-05-30 22:25
I think we should

**Comment by ryancreatescopy** [comment] 2021-06-07 14:05
> > Is the term/definition directly relevant to Ethereum?
> 
> If we include FUD do we include other trading terms? (Bull, bear, HODL, etc..)

we could do but they shouldn't block this PR. I think in general if terms get used or memed as much as the ones you mention we should add them. However we should be careful not to try and reinvent investopedia etc...

**Comment by ThePrudentPatriot** [comment] 2021-06-07 15:50
Yes, I agree. It's there any thing I should do?  To improve?

**Comment by ThePrudentPatriot** [comment] 2021-06-07 16:06
I completely agree with you in terms of not putting too many definitions.
However, I feel that F.U.D. is a definition to goes across all platforms. I
feel it fits, but also is not to reformatting. You know what I mean? Thanks
for reaching out to me! I appreciate you all working on this to make Eth
better!

**Comment by wackerow** [comment] 2021-06-24 02:25
I'm not against adding terms to the glossary, but I just want to make sure we all keep the scope of this website in mind.

- Adding terms about Ethereum should 100% be included. 
- Adding general crypto terms (FUD, HODL) should just be done with discretion imo. Some terms certainly apply to Ethereum and can help those on our website learn about the space, while others less so. Would prefer to avoid the ones that have little to no constructive role in someones process of learning about Ethereum (try to avoid an urban dictionary of crypto terms)
- The investment/market terms (bearish/bullish) I would suggest avoiding... These apply to a wide range of existing markets and have no uniqueness to Ethereum. I feel this would breach the scope of what we should be displaying on this site. 

@ThePrudentPatriot That being said, putting up a PR for the FUD definition you submitted. 

House-keeping note: Sorry for the misunderstanding at the beginning of the thread, just note we sometimes get a lot of spam, and issues that start with "FUD Fear Uncertainty Doubt" and are easily misinterpreted 😂 . Try to use the templates if possible with new issues, and give it a nice succinct title so we know what the issue is. Thanks for contributing =)

**Comment by samajammin** [comment] 2021-06-24 04:47
Ya I don't really see this as a crypto-specific term (e.g. top Google result for "fud": https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt) but I'm not strongly opposed to including this.

**Comment by ThePrudentPatriot** [comment] 2021-06-24 06:15
I had a really big definition the first submission,  but someone from your
company contacted me and said I should change it to what it says now. Sorry.

**Closed** 2021-08-05 14:24 UTC
Labels: Type: Content, Type: Feature, good first issue
