### ISSUE TITLE
Create pull request in tutorials section

### ISSUE THREAD

**Issue by AzimovS** [ethereum/ethereum-org-website#13761] opened 2024-09-01 02:15 UTC
### Describe the bug

Create pull request button on https://ethereum.org/en/developers/tutorials/ doesn't work.

### To reproduce

1. Go to 'https://ethereum.org/en/developers/tutorials/'
2. Click on 'Submit a tutorial'
3. Click on 'Create pull request'

### Expected behavior

I think it should redirect to this page https://github.com/ethereum/ethereum-org-website/tree/dev/public/content/developers/tutorials

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment] 2024-10-04 04:30
Closing as duplicate of the newer issue which as been assigned. Thanks @AzimovS

**Closed by corwintines** 2024-10-04 04:30 UTC
Labels: bug 🐛, hacktoberfest
