### ISSUE TITLE
Transfer token tutorial throws: DeclarationError: Event with same name and parameter types defined twice.

### ISSUE THREAD

**Issue by vladx777** [ethereum/ethereum-org-website#5354] opened 2022-02-07 21:20 UTC
https://github.com/ethereum/ethereum-org-website/blob/864d77178dee04e80d5f983b3911cc351118fb26/src/content/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/index.md

The above tutorial no longer works with current solidity versions, which throw this error:

DeclarationError: Event with same name and parameter types defined twice.

This is because Approval and Transfer events are declared more than once.

How could it be updated not to have this error?

**Comment by DaveyD233** [comment] 2022-05-20 05:29
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2 tokens", according to CoinBase, keeps rising 100k ETH1(&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2 tokens available, ON January 2022, to 120.1 ETH1&2 tokens IN February 2022, to NOW; Where there ARE 120.8Million ETH1(&2.0) tokens NOW, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, but Eth 2.0 is STILL Not even available to use yet!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2, is making MY Current ETHERIUM 1 tokens depreciate in value!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY LIFE! WHO KEEPS ADDING THESE "NEW TOKENS" CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! 

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by mfurkanatac** [comment] 2022-07-31 11:54
Had and still have the same problem.

**Comment by karasakalmt** [comment] 2022-11-28 16:48
I found out that you don't need to re-declare the event on the contract since it will be the same line of code they probably reducted to not re-declare on the contract. So just delete the event declerations that does exist in the interface. Better option can be keeping your events inside your interface and you can focus on the logic part on contract side.

**Comment by wackerow** [comment] 2024-01-08 17:41
If any Solidity devs out there would like to patch this tutorial, open to it =)

**Comment by karasakalmt** [comment] 2024-01-08 20:29
I can fix it @wackerow

**Comment by wackerow** [comment] 2024-01-08 22:51
Ok great! Will close this out... appreciate you taking a look @karasakalmt

**Closed by wackerow** 2024-01-08 22:51 UTC
Labels: bug :bug:, good first issue
