### ISSUE TITLE
Feature request : make colored when hover on footer icons links

### ISSUE THREAD

**Issue by Himanxu1** [ethereum/ethereum-org-website#10163] opened 2023-05-10 04:03 UTC
### Is your feature request related to a problem? Please describe.

No ,this purpose is for the  good user experience

### Describe the solution you'd like

Would like to make colored when the user hover on the links 

### Describe alternatives you've considered

no alternative 

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by Himanxu1** [comment] 2023-05-10 04:08
![etherium-footer](https://github.com/ethereum/ethereum-org-website/assets/80101755/fe64f103-5857-49d5-9e78-48153e5e5533)

Icons on the left side

**Comment by wackerow** [comment] 2024-06-10 22:53
@Himanxu1 Can you please elaborate? All items in the footer should have a hover effect that changes that color. 

https://github.com/ethereum/ethereum-org-website/assets/54227730/40ddf50b-329e-4c9f-8f5f-02e48cf69768

The only thing I'm noting is the transition duration on the social icons is slightly longer which means the color change may not be noticed if the user doesn't hover for long. Is this what you're referring to?

**Comment by corwintines** [comment] 2024-06-28 03:37
Going to close this out. @Himanxu1 if the issue still persists, feel free to reopen, but at the moment we can't reproduce this.

**Closed by corwintines** 2024-06-28 03:37 UTC
Labels: bug 🐛, question ❓
