### ISSUE TITLE
Broken Link - Rimble URL not working

### ISSUE THREAD

**Issue by raj-shekhar1** [ethereum/ethereum-org-website#3734] opened 2021-08-27 10:19 UTC
**Describe the bug**
In the `Intro to Dapp` section the link [https://rimble.consensys.design](url) is not working.

```
## Dapp tools {#dapp-tools}
**Rimble UI** **_- Adaptable components and design standards for decentralized applications._**
- [rimble.consensys.design](https://rimble.consensys.design)
```

**To Reproduce**

1. Go to  [https://ethereum.org/en/developers/docs/dapps/](url)
2. Scroll down to [https://ethereum.org/en/developers/docs/dapps/#dapp-tools](url)
3.  Click on `rimble.consensys.design`

**Expected behavior**
It should take to the home page of `rimble.consensys.design`

**Desktop (please complete the following information):**
Not required

**Smartphone (please complete the following information):**
Not required

**Additional context**
None

**Comment by enriavil1** [comment] 2021-08-28 00:57
I tried reproducing your steps, but couldn't find the link.

**Comment by enriavil1** [comment] 2021-08-28 00:58
Nevermind I see what you mean. I found it. Whenever you click the link it gives an error

**Comment by NotManyIdeasDev** [comment] 2021-08-28 10:16
I came here to report this bug, found this issue. Can confirm it's broken!

**Comment by enriavil1** [comment] 2021-08-28 10:19
I am pretty sure I could swap the links fairly quickly so I am just waiting to see if I am assigned to fix it. Also shouldn't we add this to low priority bug

**Comment by NotManyIdeasDev** [comment] 2021-08-28 10:27
Oh, I just opened a PR, I didn't know I should have waited to get assigned to the problem first...Hope it isn't a big deal!

**Comment by enriavil1** [comment] 2021-08-28 10:32
I don't know man. I am just learning how to contribute. New to this place. I don't think you will have a problem though

**Comment by enriavil1** [comment] 2021-08-28 13:05
I believe there are multiple files with the wrong rimble Url

**Comment by samajammin** [comment] 2021-08-29 20:15
Thanks for surfacing this @raj-shekhar1 (& for weighing in @NotManyIdeasDev @enriavil1)!

I commented on the PR: https://github.com/ethereum/ethereum-org-website/pull/3740#issuecomment-907864560

Curious to hear what you folks is the best approach here.

**Comment by minimalsm** [comment] 2021-08-30 10:24
Loving the enthusiasm folks ☺️ 

Appreciate your first PR on this @NotManyIdeasDev but as @samajammin highlighted this dapp should probably be removed.

As noted in #3740 because RimbleUI is no longer maintained and the example dapp does not work as intended I think we should remove it. Currently, it is referenced across 7 different translations - [see here](https://github.com/ethereum/ethereum-org-website/search?q=https%3A%2F%2Frimble.consensys.design). We should remove all 7 references to it.

Fancy taking a swing at this still @raj-shekhar1? I've assigned you, let me know if not and I'll open it back up.

**Comment by minimalsm** [comment] 2021-08-31 09:12
I've merged the broken link fix in #3740 but keeping this issue open until we remove RimbleUI.

**Comment by raj-shekhar1** [comment] 2021-08-31 11:55
Thanks @minimalsm , I would like to take this forward. 

I saw you have raised a PR and and fixed it in [https://github.com/ethereum/ethereum-org-website/pull/3740/files](url) and if it is fine I would like to raise a PR and remove it from the translations as you mentioned.

**Comment by minimalsm** [comment] 2021-08-31 12:08
@raj-shekhar1 thanks 🙏 , you're already assigned.

Just to be clear: I think we should remove this from all pages (including the English version that I updated in #3740).

**Closed** 2021-09-01 09:15 UTC
Labels: Type: Bug
