### ISSUE TITLE
Update Twitter logo

### ISSUE THREAD

**Issue by hursittarcan** [ethereum/ethereum-org-website#10797] opened 2023-07-26 19:45 UTC
## Description

* I noticed that the Twitter logo that we use on the website is not yet updated (to the new Twitter logo - [logo update Twitter](https://www.euronews.com/next/2023/07/24/twitter-to-change-logo-from-blue-bird-to-x-musk-says#:~:text=Twitter%20has%20changed%20its%20branding,platform's%20billionaire%20owner%20Elon%20Musk.)). 

### Examples of places where the logo is used
![image](https://github.com/ethereum/ethereum-org-website/assets/75273616/76ceda44-e764-40aa-b444-ce564f260a7d)
![image](https://github.com/ethereum/ethereum-org-website/assets/75273616/8e84261b-92ab-4bc8-9c94-3fd5e6ab637c)
![image](https://github.com/ethereum/ethereum-org-website/assets/75273616/2b4233de-e540-4539-8688-b03874fd5703)

### To reproduce

/

### Expected behavior

/

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by hursittarcan** [comment] 2023-07-26 19:45
Maybe a good first issue for someone?

**Comment by blazingrome** [comment] 2023-07-27 16:57
Let me see if this first can be solved.

**Comment by Astronaut828** [comment] 2023-07-31 20:40
I would like to work on this if it has not been updated yet.

**Comment by raghchawla131** [comment] 2023-08-11 08:21
Hey there,

I hope you're doing well. I've been going through the issues in our repository and I came across Issue #10797. It seems like a beginner friendly issue.

I noticed that the issue isn't assigned to anyone yet. If it's available, I'd like to take on this task and contribute to resolving it.

**Comment by corwintines** [comment] 2023-09-20 19:05
Wanting to leave my opinion here, but will seek out others.

I personally am against this change. Many apps I use are sticking to the bird logo because the unreliability of changes to Twitter/X. The brand of the bird is much more recognizable, and also not ugly. I would prefer to just keep it as is.

**Comment by corwintines** [comment] 2023-09-20 21:12
Going to close this issue out, but there is some context in the above PR that is closed.

**Closed by corwintines** 2023-09-20 21:12 UTC
Labels: bug :bug:, needs-triage
