### ISSUE TITLE
Dead link to ethereum.org/enetherscan.io

### ISSUE THREAD

**Issue by ninode97** [ethereum/ethereum-org-website#8945] opened 2022-12-18 17:54 UTC
### Describe the bug

Incorrect link href. 

It redirects to an empty page [ethereum.org/enetherscan.io](https://ethereum.org/enetherscan.io) 

Not sure if there is dedicated page for etherscan in the docs, or it should redirect to etherscan. 

### To reproduce

1. Go to 'https://ethereum.org/en/developers/docs/data-and-analytics/#block-explorers'
2. Click on 'Etherscan' 
3. See error

### Expected behavior

Should either redirect to https://etherscan.io/ or at least to internal page, that has additional information about etherscan.

### Desktop (please complete the following information)

 - OS: [Fedora Linux 37 (Workstation Edition)]
 - Browser: [brave]
 - Version: [v1.46.144]

**Comment by appsplash99** [comment] 2022-12-19 05:27
working on it...
can you please assign it to me ??

**Comment by appsplash99** [comment] 2022-12-19 07:25
Would love to get the above PR merged 😋

**Comment by egypjoy** [comment] 2022-12-19 07:48
It doesn't do that when  I hit the link it goes right to the Ethereum  official web page.

**Comment by appsplash99** [comment] 2022-12-23 18:20
@egypjoy 
The issue is still there on the prod version - click on the below link to see it in action:
'https://ethereum.org/en/developers/docs/data-and-analytics/#block-explorers'

when i hover over the _Etherscan_ link on the page;
see the incorrect url(_https://ethereum.org/enetherscan.io_) in the bottom left corner of the first image.

1st Image:  before clicking the link - _Etherscan_
![Screenshot 2022-12-23 at 11 35 07 PM](https://user-images.githubusercontent.com/65857855/209389767-5576f1cb-fa04-4b11-b45a-af787d8cb622.png)

2nd Image after clicking the link - _Etherscan_
![Screenshot 2022-12-23 at 11 46 10 PM](https://user-images.githubusercontent.com/65857855/209389792-93e399e1-27b5-412a-b767-76add150f5f9.png)

**Closed** 2023-01-19 17:58 UTC
Labels: bug :bug:
