### ISSUE TITLE
Branding guidelines -- clarify legal rights around trademark

### ISSUE THREAD

**Issue by fulldecent** [ethereum/ethereum-org-website#11752] opened 2023-12-01 17:59 UTC
(This question was originally posted in 2018 at https://github.com/ethereum/ethereum-org/issues/841 and left open with no answers.)

Current guidelines are here: https://www.ethereum.org/brand

**Please specify legal authority or "teeth" which applies to these guidelines as well as specific policies which Ethereum Foundation (EF) recognizes.** Answers should be explained clearly on the above page, but we can discuss here before then.

I am working on projects that will bring high-value real-world assets onto the blockchain. We will likely use Ethereum Mainnet -- but our lawyers have many questions. Most of them can be traced back to EF policies regarding usage of the Ethereum trademark.

# WHAT IS THE TRADEMARK

- [ ] Does *Ethereum Foundation (Stiftung Ethereum), Zug, Switzerland* express exclusive ownership over the trademarks ethereum, Ethereum, and/or the graphics shown?
- [ ] Is the trademark registered? If so where?

# WHAT IS THE LEGAL AUTHORITY

- [ ] Does Ethereum Foundation commit to police unauthorized uses of its trademarks?
- [ ] If I copy Wanchain, rename it to Ethereum and use the Ethereum logo and publish it at ethereum2.org then what is your standard response for this situation -- and what legal authority do you cite for this response?
- [ ] If a hard fork of Ethereum mainnet happens and the fork which EF supports is different than the one that the community supports then will EF exert its influence against the community variant? (Note that in this situation both will have the same "chain id", despite the best efforts of EIP-155).

# WHAT HAPPENS IF THE RELEVANCE OF ETHEREUM FOUNDATION IS THREATENED?

The present unclarity of EF's commitment and policies towards the Ethereum trademark has not caused much trouble for the community yet. EF may behave differently if it is threatened by a replacement.

- [ ] Is Ethereum Classic (a competitor) an authorized use of the Ethereum name and trademark?
- [ ] Does the EF commit to allow competitor use of the Ethereum trademark in the event that the competitor achieves market favor over the EF-supported product?*

*This is not a hypothetical question -- I want to know and clarify what is **the current policy** that EF has.

The *future situation* that such a policy would apply to is hypothetical, one example is if EF officially supports a fork, let us call it THEDAO2.0. It seems like a great idea and EF updates all software for THEDAO2.0 but actually the market favors not upgrading their clients. However the non-upgrade clients maintain the name Ethereum and the Ethereum logo and the community recognizes this network as the canonical implementation. We want to know what is EF's position should this happen.

# SUMMARY

I am working on bringing important real-world assets onto the blockchain, possibly using Ethereum. Think government-recognized ownership of land, government and industry-backed identity verification and high value assets.

**There's going to be contracts and real-world trust based on these things.**

So the contracts needs to reference something like:

- According to our smart contract, 0xabcde..., as deployed on Ethereum mainnet (CURRENTLY THIS IS UNUSABLE, IT IS NOT CLEAR WHAT ETHEREUM MEANS)
- ... as deployed on the variant of Ethereum with the largest market capitalization on coinmarketcap.com (THIS IS NOT USABLE, WHAT IS A "VARIANT"?)
- ... as deployed on network duly recognized by Ethereum Foundation (WHAT IS "DULY", WHAT IS THE GOVERNANCE PROCESS?)
- ... as deployed on Ethereum mainnet or a subsequent variant network recognized by XXX and communicated to you by XXX (where XXX is the government or other agency).

At present many major enterprise/government projects are considering hyperledger because the governance can be more clear.

# Questions

- WHAT IS THE TRADEMARK
- WHAT IS THE LEGAL AUTHORITY
- WHAT HAPPENS IF THE RELEVANCE OF ETHEREUM FOUNDATION IS THREATENED?

**Comment by fulldecent** [comment] 2024-01-16 19:16
fresh

**Comment by fulldecent** [comment] 2024-03-03 14:07
Ping

**Comment by fulldecent** [comment] 2024-04-22 08:24
.

**Comment by fulldecent** [comment] 2024-05-23 12:04
Just as important as ever

**Comment by corwintines** [comment] 2024-06-18 19:22
Thanks for bringing this up @fulldecent 

While we are ethereum.org, we dont represent the Ethereum Foundation. I will try and get some clarity though around this for you.

**Comment by fulldecent** [comment] 2024-06-23 06:03
Also, EF is claiming responsibility for the ethereum.org domain name at https://x.com/fulldecent/status/1804752152142958901

**Comment by minimalsm** [comment] 2024-06-26 12:32
Closing this as the issue is not relevant to the ethereum.org website. For questions regarding the Ethereum trademark and related rights, please reach out to the relevant parties directly. Thank you :)

**Closed as not planned** 2024-06-26 12:31 UTC
Labels: bug 🐛, needs triage 📥
