### ISSUE TITLE
Make code blocks resizable

### ISSUE THREAD

**Issue by php4fan** [ethereum/ethereum-org-website#5451] opened 2022-02-19 16:46 UTC
When I see a block of code like this:

![image](https://user-images.githubusercontent.com/13969584/154809973-3437dcf5-6365-44a4-aef8-f3e12aefb1f0.png)

(and in general anything that has a vertical scroll bar)

**I expect** to be able to click and drag the bottom-right corner to **resize it at my will**, at least vertically.

I freaking hate when I cannot.

Additionally, here, there is a button with a **misleading label "show all"** which does _not_ show all, but rather resizes it to another fixed somewhat bigger size (about twice the original height). This is making fun of the user at two levels: first, because it's called "show all", and  secondly, because it's like saying "_Oh, is this too small for you? Sorry about that, let me resize this to another fixed size that I have decided has to be enough for you_".

**Comment by wackerow** [comment] 2022-02-22 21:31
Hey @php4fan, thanks for reporting this, apologies for your frustrations.

I'm having trouble reproducing this myself, would you mind mentioning which OS and browser you're using?

**Comment by php4fan** [comment] 2022-02-23 13:15
Chrome on Linux (specifically OpenSUSE Tumbleweed).

When you say you cannot reproduce, do you mean the part where the textarea-like thingie is not resizable by dragging the bottom-right corner (I find that hard to believe that it's resizable for you), or the part where the "Show all" button doesn't show all?

Because actually the second part is no longer happening to me either. It was specifically this page (I think):
https://ethereum.org/en/developers/docs/smart-contracts/

When I clicked on "Show all", as I mentioned, it just increased the size by some arbitrary amount but not enough to reveal all the code with no scrollbar. (I retried several times and assumed that was just the way it was designed). 
That is no longer happening, so I guess it's random, or triggered under some specific conditions.

Note however that a  "show all" button is no replacement for the ability to resize the block at will. The code may be very long and I don't necessarily want to show all of it and then have the rest of the outside text miles away below. Often, I just want to increase the size of the code block arbitrarily (typically to little less than the height of the browser viewport) so I can have a glance at more code at a same time, but still keep it limited and scroll within it (as opposed to do a "show all" and then scroll the whole page), so that I don't lose track of where I an in the context of the whole page, and when I want to jump  back and forth between reading the code and reading the text that continues below (or the one before) I have both of them at a reasonable distance.

**Comment by minimalsm** [comment] 2022-02-23 15:06
Confirming I also do not see the 'Show All bug' (Brave / Safari on MacOS)

[The bottom of this tutorial has a large code block that is good for testing this.](https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/)

**Comment by samajammin** [comment] 2022-02-23 15:53
Also having trouble reproducing this bug on MacBook Air (M1, 2020) using BraveVersion 1.35.100.

Here's how things look on my end:
https://share.getcloudapp.com/04uLBYGe

> I expect to be able to click and drag the bottom-right corner to resize it at my will, at least vertically.

I don't see a bottom-right corner block like you do. I also don't share the expectation that this should be draggable for the user to resize (although I'm certainly open to that!).

> Additionally, here, there is a button with a misleading label "show all" which does not show all, but rather resizes it to another fixed somewhat bigger size (about twice the original height).

That's not the interaction I have - clicking "show all" reveals all of the code for me.

**Comment by minimalsm** [comment] 2022-03-30 10:50
Closing this out as we are unable to reproduce this anymore. Thanks for reporting!

**Comment by minimalsm** [comment] 2022-03-30 10:50
@all-contributors please add @php4fan for bugs

**Closed by minimalsm** 2022-03-30 10:50 UTC
Labels: feature :sparkles:, needs grooming

**Comment by php4fan** [comment] 2022-04-05 08:59
> Closing this out as we are unable to reproduce this anymore.

I think you are missing the relevant half of the issue.

One thing is the "show all" button not working properly: that is no longer observed and must be something that happens randomly and sporadically, so I understand not trying to address it until a way of systematically reproducing it is found.

Another thing is the **code block not being resizable** with a bottom-right handle.
The "show all" button isn't a replacement for that. Making the block resizable is trivial, it's just a matter of adding "`resize: vertical`" to the style. There's no need for any fancy javascript.
