### ISSUE TITLE
Find wallet filters that do not update when locale changes

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#12676] opened 2024-04-08 16:59 UTC
### Describe the bug

Changing the language with the language selector does not update the content where the filters are located.

### To reproduce

1. Go to https://ethereum.org/pl/wallets/find-wallet/
2. Change the language to English using the Language Picker on the top-right corner
3. Look at the filters' text in the left sidebar. They won't change, they will still be displayed in Polish

### Expected behavior

When the language is changed, the content in the left sidebar should also change to the selected language.

### Screenshots

https://github.com/ethereum/ethereum-org-website/assets/468158/6959fb42-3b7d-41cb-8930-171dc1ff1473

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by wackerow** [comment] 2024-04-08 21:02
Duplicate of #12640; closing in lieu of

**Closed by wackerow** 2024-04-08 21:02 UTC
Labels: bug :bug:, duplicate 🐥🐥
