### ISSUE TITLE
H4 sizing on /staking page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#11409] opened 2023-10-10 14:39 UTC
### Describe the bug

H4's on /staking pages appear to have grown in size to 36px from 20px.

### To reproduce

1. Go to https://ethereum.org/en/staking/#comparison-of-options
2. See size of H4's

### Expected behavior

This is what is was previously like (and would expect):

<img width="1731" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/e5a34abf-5048-4362-830e-4aafde240cde">

### Screenshots

Currently:

![image](https://github.com/ethereum/ethereum-org-website/assets/54227730/3f5794a6-327f-4602-bbf2-8268a2c46c62)

### Additional context

@nloureiro or @konopkja if you could confirm this

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by nloureiro** [comment] 2023-10-10 17:06
yes, something broke here.


this a green shot of the old Figma file
![Screen Shot 2023-10-10 05 59 04 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/e99d4511-cdfd-4ae6-8070-b24107b0b88b)


I would say to remove all the font-sizes here a let the design system default H4 style kick in.

![Screen Shot 2023-10-10 06 05 45 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/d772c217-4934-4ca8-ade9-cc8db64617f9)

**Comment by theavitw** [comment] 2023-10-10 20:04
I can do this.

**Comment by Another-DevX** [comment] 2023-10-13 03:59
i'm working on this

**Comment by suhani1804** [comment] 2023-10-16 07:46
can you assign me?

**Comment by shubhusion** [comment] 2023-11-02 19:06
Kindly assign this to me.

**Comment by konopkja** [comment] 2023-11-03 04:40
i can confirm h4 is supposed to be 20px 
![Screenshot 2023-11-03 at 9 40 02](https://github.com/ethereum/ethereum-org-website/assets/100724231/6c112c4f-bdda-4d02-b51d-60e4d030c0f8)

**Comment by shyam-patel-kira** [comment] 2023-12-07 02:41
Hi @konopkja, seems like the bug was introduced when all HTML headings were migrated to use chakraHeading instead

**Comment by Nash0509** [comment] 2024-01-02 11:03
@konopkja the core issue is because of the Chakra-heading class that is being used. So I think we should modify those H4 in order to not disturb the other bigger picture. Consider assigning it to me...

**Comment by shyam-patel-kira** [comment] 2024-01-02 20:21
@Nash0509, I've already implemented a fix for this issue [here](https://github.com/ethereum/ethereum-org-website/pull/11772).

**Comment by nloureiro** [comment] 2024-02-12 18:01
The PR fixes this >  https://github.com/ethereum/ethereum-org-website/pull/11772#pullrequestreview-1875858451

The H4 looks good. Thank you!

**Closed** 2024-02-16 19:39 UTC
Labels: bug :bug:, good first issue, needs-triage
