### ISSUE TITLE
Update stablecoins endpoint

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3312] opened 2021-06-20 20:56 UTC
**Is your feature request related to a problem? Please describe.**

New endpoint available!
See comment:
https://github.com/ethereum/ethereum-org-website/issues/2676#issuecomment-864515842

**Describe the solution you'd like**

Let's update the stablecoins page to use this 

**Describe alternatives you've considered**

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by wackerow** [comment] 2021-06-24 01:50
https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&category=stablecoins&order=market_cap_desc&per_page=100&page=1&sparkline=false

So the endpoint above that is now available pulls the top stablecoins by market cap, but this does not include the data we add to the current stablecoins being listed on ethereum.org, such as "type" (fiat vs algorithmic vs crypto vs asset backed), nor a link to a project website.  We currently have an object in `stablecoins.js` that houses this static information for a select number of tokens, but many of the now top stablecoins are not listed here (UST, LUSD, FEI...). 

If we want to list the current top dozen stablecoins, _and_ include "type" information and a link, we would either need to find another api endpoint that has this information, _or_ manually update this list with this information as the list changes. 

A more sustainable solution, though worse UX, would be to remove this information and just list the top stablecoins that result from the above query.

**Comment by DaveyD233** [comment] 2022-05-20 06:49
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by corwintines** [comment] 2022-07-19 20:02
With the work done in https://github.com/ethereum/ethereum-org-website/issues/3312, would that address the issues of this PR and let us clsoe this out?

**Comment by wackerow** [comment] 2022-07-25 18:14
@corwintines I assume you meant PR #6300 🙃 And yes, I'd say this satisfies the issue raised here. Going to close this but we can always reopen or file a new issue if we want to pursue further changes to the stablecoins page

**Closed by wackerow** 2022-07-25 18:14 UTC
Labels: feature :sparkles:, low priority, refactor ♻️
