### ISSUE TITLE
Remove algorithmic stablecoins from ethereum.org

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#6370] opened 2022-05-17 17:38 UTC
### Problem

[After the collapse of UST](https://www.coindesk.com/markets/2022/05/15/the-collapse-of-terra-was-devastating-but-there-is-still-hope-for-crypto/), the general sentiment I'm seeing in the wild is that algorithmic stablecoins are fundamentally flawed from a design perspective (E.g.: [1](https://twitter.com/TrungTPhan/status/1526572065276383232), [2](https://twitter.com/StellarOrg/status/1524794601462288385), [3](https://www.youtube.com/watch?v=lHxVRuUHJoA)). This issue aims to open up the discussion publicly about whether ethereum.org should list algorithmic stablecoins on [our stablecoins page](https://ethereum.org/en/stablecoins/) or not.

Currently, we list the top eight stablecoins based on market capitalisation. In the top eight, there are presently two algorithmic stablecoins being listed (Magic Internet Money and Frax).  

### Potential options

I see a few paths forward, but we're entirely open to all suggestions on this.

_Note: see reference images below for what the 'stablecoins list' and 'types of stablecoins' section describe._

1. Do nothing.
2. Remove algorithmic stablecoins from the 'stablecoins list' (AND remove the explanation from 'types of stablecoins'.)
3. Remove algorithmic stablecoins from the 'stablecoins list' (but keep the explanation of 'types of stablecoins'.)
4. Keep algorithmic stablecoins in the 'stablecoins list' but add a disclaimer to 'types of stablecoins' explaining that algorithmic stablecoins are experimental and not well battle-tested.

### Reference images

![stablecoinslist](https://user-images.githubusercontent.com/62268199/168875542-93c3ee07-74ae-4f82-af23-2a57502aec57.png)
![typesofstablecoins](https://user-images.githubusercontent.com/62268199/168875548-0eba2e15-ac41-4653-bd1c-3ce345ba8f1b.png)

**Comment by wackerow** [comment] 2022-05-17 17:42
Don't think we should do nothing. Think we should at least add a note of caution to the explainer card for algo's, but on the fence regarding removing from the list. 

Besides market cap, have we looked at any other metrics around these coins that could help further indicate network size and usage?

**Comment by nhsz** [comment] 2022-05-17 18:01
I'm leaning towards a mix between options 3 & 4. Algo stablecoins exist, we can't ignore them, so in terms of being informative, we should add them as a type in the 'types of stablecoin' section and add the disclaimer IMHO. 

But also think no specific algo stable should be listed for now as all of them have failed and couldn't mantain the peg (explaining this decision on the page too).

**Comment by luminoir-dustin** [comment] 2022-05-17 18:23
If we list algo stables, we should have a write up about specific risks, especially 'death-spirals' and list the graveyard of all previous failed attempts. 

George Soros' attack on the pound should also be required reading.
https://www.thebalance.com/black-wednesday-george-soros-bet-against-britain-1978944

The other tail risk about stablecoins in general is that traditional currencies have controls on them like withdrawal freezes, currency expropriation limits, travel carry declarations to prevent market contagion, bank runs and similar mass hysteria events. 

In the crypto space, these are regarded as anathema, so such circuit breakers don't typically don't exist, not because they can't be done, but because they aren't 'values aligned'. This means currencies can potentially move from the crypto equivalent of M2-M4 at the speed of the network confirmation rate depending on the nature of the transaction. It also means that pulling up the drawbridge in these circumstances isn't available as an option in the toolkit.

**Comment by strifedefi** [comment] 2022-05-17 20:46
I'm leaning towards option 4 as I do believe they'll be around for some time.

Provide a summary of the types of stablecoins, inherent risks, and examples of failures.

**Comment by corwintines** [comment] 2022-05-17 21:15
I'm most in favor of option 3 or 4. I think it's important to talk about them still, but I do think we need to do something to bring awareness of the risk a bit more on the ones that are listed. We currently have a list we filter down to which I think needs to be reassessed as part of this issue. This list includes all stables being listed on the page, and part of that could be looking into risky patterns (unreasonable yields) for these coins that should be red flags and a reason to remove. Overall, mostly just think we need to do a bit of an audit on that page, with a focus on risks users may face. The name stablecoin gives a false sense of security I think for users, and it's clear you must do some due diligence as a user on your stables.

**Comment by robriks** [comment] 2022-05-18 02:37
Option 4 seems most reasonable seeing as Terra mkt cap was 2/3 Lehman / small country size. Algostables are too large to ignore and people will continue designing them, potentially someday achieving sustainability but w/ many failures along the way.

In addition to option 4, I think the current stablecoins list could benefit from adding a superscript disclaimer in the 'COLLATERAL TYPE' field next to the 'Algorithmic' value. Something along the lines of:  

*Experimental
or
*Controversial

**Comment by AstronautSleuth** [comment] 2022-05-18 02:48
4 because VCs will continue to fund projects who are building algo stablecoins as the upside is extremely large should 1 succeed.

Here's a very good twitter thread on the game DK was playing https://twitter.com/gametheorizing/status/1526373843908153345

But we should definitely add more links & resources regarding token design or an explanation of how the death spiral works & post mortem of IRON/Titan, UST etc.

**Comment by samajammin** [comment] 2022-05-19 09:29
I also vote for option 4

> Keep algorithmic stablecoins in the 'stablecoins list' but add a disclaimer to 'types of stablecoins' explaining that algorithmic stablecoins are experimental and not well battle-tested.

I think it's too early to completely dismiss algorithmic stablecoins. I don't think it's ethereum.org's job to completely write them off at this point - that's for the broader market/industry to decide. Experimentation in this field will no doubt continue & I think we can continue to display them.

That said, I agree they should be labeled as experimental given no attempts have yet proven themselves sustainable. We should include warnings to DYOR. Examples of notable failures also sounds like a reasonable approach so users are going in with eyes open.

While we're reassessing risks to display on algorithmic, I think we could also look at other types, e.g how fiat-backed stables often have the ability to freeze tokens & black list addresses.

**Comment by saintsal** [comment] 2022-05-19 09:57
Some random dude had a nice point about distinguishing between over- and under-collateralised stables.  :) https://twitter.com/VitalikButerin/status/1525512307358347265

It strikes me this distinction is a lot clearer, easier to understand (for learners) and to categorise (for list maintainers).  Whereas trying to maintain a list of projects and their various categories of "how algorithmic" will problem get difficult and messier as time passes.

Are there any guiding policies about how ethereum.org deals with implied endorsement to projects, stewarding newbies safely and/or mapping the ecosystem?

My two cents: since ethereum.org is considered a 'trusted' source to newbies, focusing on educating people on the ways to categorise and evaluate risks would be constructive for newcomers and maintain neutrality.

**Comment by DaveyD233** [comment] 2022-05-20 05:25
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2 tokens", according to CoinBase, keeps rising 100k ETH1(&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2 tokens available, ON January 2022, to 120.1 ETH1&2 tokens IN February 2022, to NOW; Where there ARE 120.8Million ETH1(&2.0) tokens NOW, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, but Eth 2.0 is STILL Not even available to use yet!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2, is making MY Current ETHERIUM 1 tokens depreciate in value!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY LIFE! WHO KEEPS ADDING THESE "NEW TOKENS" CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! 

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by jmcook1186** [comment] 2022-05-20 12:46
I vote for option 4 - keep them in the list but clearly labelled as algorithmic. Then we should have a clear explanation of the risks associated with algo stables and links out to details of past failures.

**Comment by wackerow** [comment] 2022-05-24 00:47
I feel convinces personally. Sounds like there is heavy support for option 4: keeping algo's listed, but offering additional education / warnings around them. I agree @samajammin that it should not be up to the ethereum.org team to exile an entire category of projects. I prefer education. 

I agree with the other comments to also add scrutiny to the other categories. Algo's have had a rough path, but the other categories aren't free from problems either as some have alluded to, and we should highlight this.

Given this isn't on our current roadmap, I suggest we first:
- [x] List only Ethereum stables to begin with
- [ ] Keep unbiased list of top coins and their categories, marking "algos" with an asterisk
- [ ] Add a simple \* caution note to the Algo card at the bottom, noting high risk category and history of some catastrophic outcomes.

Longer-term
- Audit that whole page and perform risk assessment of all categories, and more adequately display risks of all types of stables.
- Go into more detail on the risks of algos (or any other particular risk that surfaces through that research for the other categories)

**Comment by wackerow** [comment] 2022-06-06 18:52
Another thought on how these tokens are organized... Right now we break stables into fiat backed, crypto backed, precious metal backed, and algorithmic. 

There are "algorithms" involved in tokens like DAI as well... we could consider adjusting the name of the algo section to something like "Incentive-based non-collateralized" or "under-collateralized" to make this category more explicit about what backs it (or doesn't back it), and to differentiate it from "over-collateralized" projects (ie DAI). Huge difference in risk here, and this could help make it more transparent, in an ELI-5 sense.

**Comment by corwintines** [comment] 2024-02-08 18:39
To close this issue out, we would like to go with option 4. We would like to add a disclaimer for stablecoins to this page, outlining the risks. 

This whole page needs to be overhauled at this point, but the disclaimer would get this issue across the finish line. 

Leaving it open for someone to pick up if they would like :)

**Comment by wackerow** [comment] 2024-02-12 18:26
Still desired, opening this up for anyone looking to contribute ❤️

**Comment by wackerow** [comment] 2024-02-15 18:48
Looks like we've form consensus here around going with option 4... I've opened a new issue with this specific task to provide clarity to contributors. Closing this one out in lieu of this new issue.

**Closed by wackerow** 2024-02-15 18:48 UTC
Labels: content :fountain_pen:, proposal 🤔, good first issue, dev required
