### ISSUE TITLE
Change Twitter Logo to X Logo

### ISSUE THREAD

**Issue by aj-ats** [ethereum/ethereum-org-website#13103] opened 2024-06-03 14:41 UTC
### Is your feature request related to a problem? Please describe.

There is no Problem related  with the twitter logo 

### Describe the solution you'd like

Change twitter logo to X logo using the provided toolkit  https://about.x.com/en/who-we-are/brand-toolkit 
- ensure formatted properly across mobile/desktop devices 

### Describe alternatives you've considered

no  alternative solutions 

### Would you like to work on this issue?

- [x] Yes
- [ ] No

**Comment by aj-ats** [comment] 2024-06-03 14:42
@bhappy-buidl

**Comment by wackerow** [comment] 2024-06-07 13:43
Duplicate of #12379, cc: @nloureiro

**Closed by wackerow** 2024-06-07 13:43 UTC
Labels: duplicate 🐥🐥
