### ISSUE TITLE
UI Bug report: menu item remove bold

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13499] opened 2024-07-26 07:29 UTC
### Describe the bug

Seeing mobile menu navigation, one subsection called "emerging use cases" has subtext in bold, which it should not be. The normal text should be used instead.

### To reproduce

1. Go to https://ethereum.org/en/
2. Click on the menu on **Mobile device**
3. Select "Use"
4. Select "use cases"
5. See error - "Emerging usecases" the subtext has bold and it should not

### Expected behavior

Remove bold on subtext

### Screenshots

![Screenshot 2024-07-26 at 12 25 32](https://github.com/user-attachments/assets/bc13bf6d-9ad4-4057-96a5-239775e05dcf)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by sanjanaynvsdl** [comment] 2024-07-26 12:08
Hey @konopkja, 
I would like to work on this issue can you please assign this to me?

**Comment by konopkja** [comment] 2024-07-26 15:35
Hey, assigned, thank you :)

**Comment by rohitt-gupta** [comment] 2024-08-04 08:22
Is this issue still there?
not able to reproduce though.
![image](https://github.com/user-attachments/assets/ad5d0237-49b2-4b36-ba6d-12c0de700b4c)

**Comment by bajshorya** [comment] 2024-08-05 19:32
hey @konopkja i just made a PR solving this issue ! Can you have look !

**Closed** 2024-08-06 20:24 UTC
Labels: bug 🐛, help wanted, good first issue, dev required
