### ISSUE TITLE
Create Rentable NFTs Using ERC-4907 Standard

### ISSUE THREAD

**Issue by chandn0** [ethereum/ethereum-org-website#10713] opened 2023-07-18 18:14 UTC
### Tutorial title

Create Rentable NFTs Using ERC-4907 Standard

### Tutorial description

In this tutorial, we will guide you through the step-by-step process of creating Rentable NFT smart contracts. 

### Tutorial tags

NFT, Solidity, Smart Contract

### Skill level

Beginner

### Hosted on ethereum.org or hosted elsewhere?

Hosted elsewhere

### For tutorials hosted elsewhere: URL to tutorial

https://www.buildbear.io/resources/guides-and-tutorials/Rentable_NFTs

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment] 2024-06-11 17:39
Duplicate of #10712, closing

**Closed by wackerow** 2024-06-11 17:39 UTC
Labels: duplicate 🐥🐥
