### ISSUE TITLE
Migrate materials from eth.wiki

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#5690] opened 2022-03-17 15:45 UTC
## Background

The material hosted at eth.wiki is now very stale and contains information that is years out of date. This can be confusing for users because the old information can contradict newer information available elsewhere and it is not clear what the canonical source of information should be. While the wiki is rich with Ethereum history, it seems like a good time to migrate some information from those sites onto ethereum.org and sunset those older sites.

There have been several suggestions along similar lines recently but so far only relatively minor actions have been taken, e.g.

https://github.com/ethereum/eth-wiki/issues/55

Therefore, I'm raising this issue to jump-start progress on this and get the good content from the wiki migrated over to ethereum.org.

## Proposal

I have been through the wiki page by page and made suggestions for which materials I think should be migrated to ethereum.org and which materials should be archived/taken offline. Below is a table with those file-by-file suggestions. Underneath the table is a high level summary of the actions that could be taken int he form of 12 PRs to ethereum.org to preserve the good information currently only available in the wiki.
              
                    

```                    
|   Suggestions     |                  Notes                         |  File                                          |
|-------------------|------------------------------------------------|------------------------------------------------|
|                   |                                                ├── archive                                      |
|Sunset             | redirect to eth.foundation                     │   ├── licensing.md                             |
|                   |                                                |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | historically interesting but uneccessary       │   ├── poll-for-token-proposal-EIP-20.md        |
|                   | redirect to /developers/docs/standards/        |   |                                            |
|                   | tokens/erc-20/                                 |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | redirect to eth.org                            │   ├── proposal-reversion-notification.md       |
|                   | /developers/docs/apis/json-rpc                 |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | redirect to eth.org                            |   ├── proposal-transaction-proxy-hooks.md      |
|                   | /developers/docs/apis/json-rpc                 |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | OOD redirect to eth.org                        │   └── serpent.md                               |
|                   |  (/docs/smart-contracts/languages/             |                                                |
|                   |                                                |                                                |
|                   |                                                ├── clients                                      |
|                   |                                                |   |                                            |
|Sunset             | OOD redirect to eth.org                        │   ├── clients-tools-dapp-browsers-wallets...   |
|                   | (developers/docs/nodes-and-clients)            |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Client teams include in their own docs,        |   ├── client-version-strings.md                |
|                   | but migrate to nodes & client page             |   |                                            |
|                   |                                                |   |                                            |
|                   | OOD and superceded by existing tutorials on    │   └── geth-dapp-loading-proposal.md            |
|                   | eth.org                                        |                                                |
|                   |                                                |                                                |
|                   |                                                ├── concepts                                     |
|Update and migrate | OOD & incomplete but there is currently no     │   ├── adaptive-message-ids.md                  |
|                   | information about how the P2P network operates |   |                                            |
|                   | on eth.org - it couild be good to include a    |   |                                            |
|                   | med-high level explanation.                    |   |                                            |
|                   |                                                |   |                                            |
|Partial migrate    | Some mention of timing could go in new p2p     │   ├── adaptive-peer-time.md                    |
|                   | or networking page                             |   |                                            |
|                   |                                                |   |                                            |
|Expand and migrate | OOD and incomplete but relatively detailed     │   ├── casper-proof-of-stake-compendium.md      |
|                   | explanation of the fork-choice algorithm and   |   |                                            |
|                   | finality gadget would be good to add to eth.org|   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Historically interesting but unnecessary       │   ├── dagger-hashimoto.md                      |
|                   |                                                |   |                                            |
|Expand and migrate | currently no mention of ENS on eth.org         │   ├── ens                                      |
|                   | redirect to ens docs                           │   │   └── ens.md                               |
|                   |                                                |   |                                            |
|Partial migrate    | high level explanation of ethhash algorithm    │   ├── ethash                                   |
|                   | and its diffs to bitcoin equivalent could be   |   |   |                                        |
|                   | nice to have on eth.org, but specifics seem    |   |   |                                        |
|                   | uneccessary now that mining is shutting down.  |   |   |                                        |
|                   |                                                │   │   ├── c-api.md                             |
|                   |                                                │   │   ├── dag-disk-storage-format.md           |
|                   |                                                │   │   ├── dag.md                               |
|Migrate            | combine design-rationale and ethhash pages     │   │   ├── design-rationale.md                  |
|Migrate            | into shorter, higher level explanation and     │   │   └── ethash.md                            |
|                   | add to eth.org                                 |   |                                            |
|                   | (developers/docs/consensus-mechanisms/pow/)    |   |                                            |
|                   |                                                |   |                                            |
|                   |                                                │   ├── evm                                      |
|Sunset             | Uneccessary for eth.org                        │   │   ├── create-create2-comparison.md         |
|Update and Migrate | Lots of OOD info but overall useful to have    │   │   ├── ethereum-virtual-machine-(evm)...    |
|                   | some of this on eth.org by adding to           |   |   |                                        |
|                   | /developers/docs/evm/                          |   |   |                                        |
|                   |                                                |   |   |                                        |
|Sunset             | lots of material duplicated from eth.wiki/     │   │   ├── evm.md                               |
|                   | evm/ethereum-virtual-machine-(evm)-awesome-list|   |   |                                        |
|                   |                                                |   |   |                                        |
|Sunset             | redirect to eth.org (developers/docs/evm/)     │   │   └── implementations.md                   |
|                   |                                                |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Superfluous for eth.org, info in client docs   │   ├── extra-date-standard.md                   |
|                   | and ethereum specs                             |   |                                            |
|                   |                                                |   |                                            |
|Update and migrate | Info on wiki is out of date but light client   │   ├── light-client-protocol.md                 |
|                   | info (EL and CL) would be good addition to     |   |                                            |
|                   | eth.org, probably under                        |   |                                            |
|                   | developers/docs/nodes-and-clients/             |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | More up to date info on block explorers already|   ├── network-status.md                        |
|                   | available, redirect to eth.org                 |   |                                            |
|                   | (developers/docs/data-and-analytics/           |   |                                            |
|                   | block-explorers/)                              |   |                                            |
|                   |                                                |   |                                            |
|Migrate            | Lots of useful information that could be used  │   ├── proof-of-stake-faqs.md                   |
|                   | to build out more PoS resources on eth.org     |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Interesting but superfluous - security         │   ├── security-categorization.md               |
|                   | considerations for X component can be discussed|   |                                            |
|                   | in component X\'s page instead of a separate   |   |                                            |
|                   | security page.                                 |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | OOD and largely covered in tutorials and token │   ├── standardized-contract-apis.md            |
|                   | standard pages on eth.org. Info on multisigs   |   |                                            |
|                   | could be a useful addition to eth.org though.  |   |                                            |
|                   |                                                |   |                                            |
|Potential migrate  | Currently not much info on swarm on eth.org    │   ├── swarm-hash.md                            |
|                   | but perhaps the current                        |   |                                            |
|                   | /developers/docs/storage/ page that links to   |   |                                            |
|                   | swarm docs is sufficient?                      |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Can\'t find any up to date info on url-hint    │   ├── url-hint-protocol.md                     |
|                   | and think it is long OOD.                      |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Page is just a few links to OOD tutorials.     │   ├── useful-dapp-patterns.md                  |
|                   | Already superceded by tutorials on eth.org     |   |                                            |
|                   | Redirect to eth.og/developers/tutorials        |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | AFAIK whisper had some fundamental issues that │   ├── whisper                                  |
|                   | killed it long ago and development of p2p      │   │   ├── overview.md                          |
|                   | messaging is now dominated by waku. Suggest    │   │   ├── poc-2-protocol-spec.md               |
|                   | killing this whole folder and considering      │   │   ├── poc-2-wire-protocol.md               |
|                   | a new page on p2p messaging on eth.org later.  │   │   ├── whisper.md                           |
|                   | Then redirect to that page                     │   │   ├── whisper-overview.md                  |
|                   |                                                │   │   └── wire-protocol.md                     |
|Sunset             | Superceded by rollup-centric roadmap           │   └── wishlist.md                              |
|                   | redirect to eth.org  upgrades/vision/          |                                                |
|                   |                                                |                                                |
|Sunset             | These are only skeleton pages on the wiki      ├── enterprise                                   |
|                   | and the concepts are well explained on         │   ├── enterprise.md                            |
|                   | eth.org already                                │   └── whymainnet.md                            |
|                   |                                                |                                                |
|Sunset             | Very interesting to see materials from ACD meet├── eth1                                         |
|                   | in Berlin but long OOD. Kill whole dir         │   ├── clients.md                               |
|                   |                                                │   ├── coredevsberlin.md                        |
|                   |                                                │   └── eth1.md                                  |
|Sunset             | OOD info, eth.org already covers in more detail├── eth2                                         |
|                   | Suggest killing whole dir                      │   ├── clients.md                               |
|                   |                                                │   └── eth2.md                                  |
|                   | OOD info, eth.org already covers in more detail├── faqs                                         |
|                   | Suggest killing whole dir                      │   ├── famous-bugs.md                           |
|                   |                                                │   ├── faqs.md                                  |
|                   |                                                │   ├── glossary.md                              |
|                   |                                                │   ├── major-issues-resulting-in-lost...md      |
|                   |                                                │   ├── problems.md                              |
|                   |                                                │   └── subtleties.md                            |
|                   |                                                |                                                |
|                   |                                                ├── fundamentals                                 |
|                   |                                                |   |                                            |
|Sunset             | OOD since 2016, not needed on eth.org          │   ├── benchmarks.md                            |
|                   |                                                |   |                                            |
|Sunset             | OOD, redirect to eth.org /developers/docs      │   ├── dapp-developer-resources.md              |
|                   |                                                |   |                                            |
|Sunset             | OOD, redirect to eth.org/developers/docs       │   ├── dapp-development.md                      |
|                   |                                                |   |                                            |
|Sunset             | OOD,historically fascinating, but already well │   ├── decentralized-apps-dapps.md              |
|                   | covered on eth.org/developers/docs             |   |                                            |
|                   |                                                |   |                                            |
|Migrate            | Very interesting and not covered on eth.org,   │   ├── design-rationale.md                      |
|                   | possible update and migrate?                   |   |                                            |
|                   |                                                |   |                                            |
|Migrate            | No mention of enode-url on eth.org, superceded │   ├── enode-url-format.md                      |
|                   | by ENR - add page on ENR and link from new     |   |                                            |
|                   | networking layer page. Redirect to ENR page.   |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Mostly covered on eth.org, but potentially     │   ├── ethereum-introduction.md                 |
|                   | update/migrate quantum resistance info?        |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Mostly covered on eth.org, but info on Particia|   ├── fundamentals.md                          |
|                   | merkle trees, rlp and enodes could be migrated |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | OOD and already well covered on eth.org        │   ├── getting-ether.md                         |
|                   |                                                |   |                                            |
|Sunset             | OOD and already well covered on eth.org        │   ├── getting-started.md                       |
|                   |                                                |   |                                            |
|Sunset             | OOD and already well covered on eth.org        │   ├── mining.md                                |
|                   |                                                |   |                                            |
|Migrate            | Info not currently well covered on eth.org.    │   ├── patricia-tree.md                         |
|                   | Sugest at minimum updating glossary entry      |   |                                            | 
|                   | but possibly adding new page                   |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Dead link and already well covered on eth.org  │   ├── programming-languages-intro.md           |
|                   |                                                |   |                                            |
|Migrate            | Add to new networking layer page               │   ├── rlp.md                                   |
|                   |                                                |   |                                            |
|Sunset             | Info covered by links to up to date spec repos │   ├── specs                                    |
|                   |                                                │   │   ├── bad-block-reporting.md               |
|                   |                                                │   │   ├── chain-spec-format.md                 |
|                   |                                                │   │   └── consensus-datastructures.md          |
|Sunset             | Covered already on eth.org                     │   ├── testnets.md                              |
|                   | (developers/docs/networks)                     |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Covered already on eth.org                     │   └── what-is-ethereum.md                      |
|                   | (what-is-ethereum/)                            |                                                |
|                   |                                                |                                                |
|Sunset             | Covered already on eth.org                     ├── funding                                      |
|                   |  (/community/grants/) - kill whole dir         │   ├── experiments.md                           |
|                   |                                                │   └── funding.md                               |
|                   |                                                ├── governance                                   |
|                   |                                                |   |                                            |
|Sunset             | Contribution guidelines are clearly explained  │   ├── 5-strategies-of-contribution.md          |
|                   | for ethereum.org and ethereum repos            |   |                                            |
|                   |                                                |   |                                            |        
|Migrate            | It would be a nice addition to have the        |   ├── communitycalls.md                        |
|                   | details of community calls on eth.org          |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | No longer relevant                             │   ├── contributing.md                          |
|                   |                                                |   |                                            |
|Sunset             | No longer relevant                             │   ├── gitter-channels.md                       |
|                   |                                                |   |                                            |
|Migrate            | Some very interesting material and useful      │   ├── governance-compendium.md                 |
|                   | diagram that could find a home in the          |   |                                            |
|                   | pages on eth.org                               |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Some interesting but OOD info - I think most   │   ├── infrastructure.md                        |
|                   | of the relevant material is already on eth.org |   |                                            |
|                   | across several pages but particularly          |   |                                            |
|                   | /community/online                              |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | OOD and no longer relevant                     │   ├── maintainers.md                           |
|                   |                                                |   |                                            |
|Sunset             | This is just a skeleton page w internal links  │   ├── polices-and-guidelines.md                |
|                   |                                                |   |                                            |
|Expand and migrate | Information about responsibel discolusures of  │   └── security-issue-process.md                |
|                   | protocol bugs is not easily accessible on      |                                                |
|                   | eth.org at the moment. Also bug bounty info.   |                                                |
|                   |                                                |                                                |
|Sunset             | No longer relevant                             ├── home.md                                      |
|                   |                                                |                                                |
|                   |                                                ├── howto                                        |
|Sunset             | OOD and better to link to client docs          │   ├── blockchain-import-and-export...md        |
|                   |                                                |   |                                            |
|Sunset             | dead link but also OOD and covered by          │   ├── dapp-using-meteor.md                     |
|                   | existing tutorials on eth.org                  |   |                                            |
|                   |                                                |   |                                            |
|                   | OOD and well covered by existing tutorials     │   ├── ethereum-development-tutorial.md         |
|                   | on eth.org (although the bytecode instructions |   |                                            |
|                   | are nice -probably too low level for eth.org   |   |                                            |
|                   |                                                |   |                                            |
|Sunset             | Well covered by                                │   └── smart-contract-safety.md                 |
|                   | /developers/docs/smart-contracts/security/ page|                                                |
|                   | on eth.org                                     |                                                |
|                   |                                                |                                                |
|Sunset             | Historically interesting but no longer relevant├── ideas                                        |
|                   | Suggest killing whole dir                      │   ├── bad-chain-canary.md                      |
|                   |                                                │   ├── deterministic_wallet_spec.md             |
|                   |                                                │   ├── distributed-preimage-archive.md          |
|                   |                                                │   ├── erc-735.md                               |
|                   |                                                │   ├── hpoc_2015.md                             |
|                   |                                                │   ├── inter-exchange-client-address...md       |
|                   |                                                │   ├── ipv6.md                                  |
|                   |                                                │   ├── kademlia-peer-selection.md               |
|                   |                                                │   ├── middleware-and-dapp-project-ideas.md     |
|                   |                                                │   ├── newblockfilter-improvement-proposal.md   |
|                   |                                                │   └── parallel-block-downloads.md              |
|Sunset             | Very high level overview already available on  ├── json-rpc                                     |
|                   | eth.org at /developers/docs/apis/json-rpc/     |   |                                            |
|                   | it might be good to migrate some of this info  |   |                                            |
|                   | and expand the eth.org page, but perhaps       |   |                                            |
|                   | linking to external resources is enough.       |   |                                            | 
|                   |                                                │   ├── api.md                                   |
|                   |                                                │   └── error-codes-improvement-proposal.md      |
|                   |                                                |                                                |
|Sunset             | OOD and superceded by ethresear.ch, R&D discord|── research                                     |
|                   | suggest killing entire dir                     │   ├── alternative-blockchains-randomness...    |
|                   |                                                │   ├── ewasm-compendium.md                      |
|                   |                                                │   ├── formalverification.md                    |
|                   |                                                │   ├── node-discovery-protocol.md               |
|                   |                                                │   ├── rd.md                                    |
|                   |                                                │   ├── registrar-abi.md                         |
|                   |                                                │   ├── relay-projects.md                        |
|                   |                                                │   ├── scaling-projects-and-proposals-..        |
|                   |                                                │   └── storage-projects.md                      |
|Sunset             | OOD. Rollup-centric roadmap already explained  ├── roadmap                                      |
|                   | on eth.org and historical upgrades already     │   ├── berlin.md                                |
|                   | explained at /history/ page                    │   ├── byzantium-hard-fork-changes.md           |
|                   |                                                │   ├── istanbul                                 |
|                   |                                                │   │   └── tracker.md                           |
|                   |                                                │   ├── istanbul.md                              |
|                   |                                                │   ├── london.md                                |
|                   |                                                │   ├── muir_glacier.md                          |
|                   |                                                │   ├── petersburg.md                            |
|                   |                                                │   ├── releases.md                              |
|                   |                                                │   └── roadmap.md                               |
|Sunset             | OOD redirect to eth.org                        ├── scalability                                  |
|                   | /developers/docs/scaling/                      │   └── chain-fibers-redux.md                    |
|                   |                                                |                                                |
|Sunset             | OOD redirect to eth.org                        ├── sharding                                     |
|                   |  /developers/docs/scaling/                     │   ├── ethresearch-sharding-compendium.md       |
|                   |                                                │   ├── Sharding-FAQs.md                         |
|                   |                                                │   ├── sharding-introduction-r-d-compendium.md  |
|                   |                                                │   └── sharding-ro                              |
```           
     

## Actions

The following 12 items are materials either present in the wiki and absent on ethereum.org, or explained in much more detail on the wiki that I suggest could be incorporated into ethereum.org. Suggest each one could be tacked as a separate PR:

1. [PoS consensus with FAQs](https://eth.wiki/concepts/proof-of-stake-faqs) - use materials from wiki to rework existing PoS page. **UPDATE: ADDRESSED BY PR:** #6157 (also decided not to migrate FAQs as they are already available verbatim at vitalik.ca)
2. [Fork choice algorithm and finality gadget](https://eth.wiki/concepts/casper-proof-of-stake-compendium) - not currently discussed in detail on ethereum.org - use material from wiki to rework PoS page? **UPDATE: ADDRESSED BY PR:** #6157
3. [Light Clients](https://eth.wiki/en/concepts/light-client-protocol) - currently briefly mentioned for EL but not CL - use material from wiki to expand /nodes-and-clients/. **UPDATE: ADDRESED BY PR:** #6223
4. Network Layer - there is a lot of info on the networking layer in several pages on the wiki and very little on ethereum.org - new page. Start new page and initially add it to developers/docs/. Should include landing page and link to new pages on ENR, possibly p2p messaging (whisper/waku) and light clients, and to existing pages on decentralized storage. **UPDATE: ADDRESSED BY PR** #5838 
5. Multisigs - briefly mentioned on wiki, not mentioned on ethereum.org - add material from wiki to /developers/docs/smart-contracts/. **UPDATE: Addressed by PR:** #6225 
6. [Design rationale](https://eth.wiki/en/fundamentals/design-rationale) - very interesting material on ethereum design rationale that could be reworked for ethereum.org - new page? **UPDATE: addressed by PR:** #5935
7. [Security disclosure protocol](https://eth.wiki/en/governance/security-issue-process) - explained on wiki but not on ethereum.org - suggest new page clearly explaining how to disclose bugs and bug bounties? **UPDATE:** this is being handled by another team - no need to address this here anymore.
8. Quantum resistance - mentioned in wiki but not on website - not sure where this would fit best on website if anywhere (probably best aimed at a EF blog post by someone at some point?). **UPDATE**: ignoring this idea - the info on wiki is actually very limited and this is best dealt with in future "research" section of ethereum.org.
9. [Patricia merkle trees](https://eth.wiki/en/fundamentals/patricia-tree) - migrate info from wiki into new "data structures" page. **UPDATE: ADDRESSED BY PR** #5758
10. [Recursive-length prefix](https://eth.wiki/en/fundamentals/rlp) - explained on wiki, not on website - incorporate into new data-structures page **UPDATE: ADDRESSED BY PR** #5758
11. [P2P messaging](https://eth.wiki/en/concepts/whisper/whisper) - potentially incorporate into networking layer page?
12. [pow mining-dagger](https://eth.wiki/concepts/dagger-hashimoto) and [pow-mining-ethash](https://eth.wiki/concepts/ethash/ethash) substantial parts of this material could be migrated to ethereum.org, partly expanding the existing pow mining page and probably also adding new pages for mining algorithms.
 **UPDATE: ADDRESSED BY PR** #5897

The wiki could then be sunsetted by redirecting to appropriate pages on ethereum.org or external sites.

After discussion with the ethereum.org team, materials related to Swarm and ENS are best redirected to their individual sites rather than migrating the information onto ethereum.org.

## Linked issues
- part of the "Consolidate Ethereum wikis" epic in our Q2 roadmap (#6161)
- related to #5731
- https://github.com/ethereum/ethereum-org-website/issues/2324
- https://github.com/ethereum/ethereum-org-website/issues/2325
- https://github.com/ethereum/eth-wiki/issues/55

**Comment by samajammin** [comment] 2022-03-18 15:49
Relates to #2324 & #2325

**Comment by samajammin** [comment] 2022-04-06 07:12
Awesome, thanks for digging into this!

Looking through some of you specific page recommendations...

```
|Sunset             | Uneccessary - client teams include in their    |   ├── client-version-strings.md                |
|                   | own docs, not relevant for eth.org readers     |   |                                            |
```

Is this something all clients still do? Should we perhaps add a section within https://ethereum.org/en/developers/docs/nodes-and-clients/ that touches on this, so people are aware it exists?

I can also see your point that we could leave that to each client team to document on their own. It does seem a bit of an advanced topic to cover. In that case, **what should we do with this page?**. We should still redirect it _somewhere_ if we're going to kill it. I'd say https://ethereum.org/en/developers/docs/nodes-and-clients/ is better than nothing. A general note I'd say is that we should try to avoid sunsetting a page but not redirecting it anywhere (i.e. don't break the internet). We should at least try to redirect to the most relevant page so users have the best chance to eventually find what they're looking for.

...that's all I have time for now 😅 I'll try to circle back this week to review the rest!

**Comment by jmcook1186** [comment] 2022-04-11 13:04
> Awesome, thanks for digging into this!
> 
> Looking through some of you specific page recommendations...
> 
> ```
> |Sunset             | Uneccessary - client teams include in their    |   ├── client-version-strings.md                |
> |                   | own docs, not relevant for eth.org readers     |   |                                            |
> ```
> 
> Is this something all clients still do? Should we perhaps add a section within https://ethereum.org/en/developers/docs/nodes-and-clients/ that touches on this, so people are aware it exists?
> 

ok! I can certainly add a note to the existing nodes and clients page that can then be linked out to. Will update table accordingly.

**Comment by DaveyD233** [comment] 2022-05-20 06:53
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by samajammin** [comment] 2022-06-07 02:40
@jmcook1186 I think we can close this out - great work! Feel free to re-open if you think we missed anything.

**Closed by samajammin** 2022-06-07 02:40 UTC
Labels: feature :sparkles:

**Comment by kuzdogan** [comment] 2022-06-17 12:16
Reporting that I receive a 404 from the eth.wiki page https://eth.wiki/fundamentals/rlp which was the top search result in "RLP_encode" and "recursive length prefix". 

I don't think a mapping to each old eth.wiki to ethereum.org docs is feasible but a catch-all redirect to https://ethereum.org or https://ethereum.org/en/developers/docs/ might make sense
