### ISSUE TITLE
The Run a node page and Translators guide don't show up on the search

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#5268] opened 2022-01-29 17:49 UTC
**Describe the bug**

When searching for Run a node or Translation style guide on the website, the search doesn't show the latest pages.

**To Reproduce**

1. Go to ethereum.org
2. Type 'Run a node' or 'Translation style guide' in the search bar
3. See error

**Expected behavior**

The search should show the newly added pages.

**Screenshots**

![Search error 1](https://user-images.githubusercontent.com/37338979/151671680-41bca0a6-b4f5-490a-880a-c13210a88c6b.png)
![Search error 2](https://user-images.githubusercontent.com/37338979/151671681-066bfd4a-596d-4f2b-99cd-c9d2ec9c913a.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: V1.34.81

**Comment by aforamit** [comment] 2022-01-31 08:38
I tried to follow the steps as described and my observation are as follows: 

- _run a node_ : The result is not top of the list, but appears in the middle. See below

<img width="887" alt="run a node" src="https://user-images.githubusercontent.com/22254168/151762319-86171108-7b85-4b26-8172-a8aac683f4d0.PNG">

- _translation style guide_ : the results are shown correctly on top of the list. See below
<img width="893" alt="translation style guide" src="https://user-images.githubusercontent.com/22254168/151762436-5cc83b2a-21d3-4314-b6d0-9940056362a3.PNG">

Can you please check and clarify if the issue persist? Or provide more details.

**Comment by minimalsm** [comment] 2022-01-31 09:15
Hey @aforamit, thanks for checking in on this. @lukassim is referring to [this page](https://ethereum.org/en/run-a-node) that we newly released. 

Seems the issue is solved now. Closing this out.

**Closed** 2022-01-31 09:15 UTC
Labels: bug :bug:
