### ISSUE TITLE
Investigate ways to reduce noise of build logs

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2810] opened 2021-04-08 20:44 UTC
**Is your feature request related to a problem? Please describe.**

We're getting a bunch of "Query takes too long" warnings during site builds, e.g.

```
warn Query takes too long:
File path: /Users/samrichards/code/ef/ethereum-org-website/src/templates/tutorial.js
URL path: /lt/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/
Context: {
    "slug": "/lt/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/",
    "isOutdated": false,
    "isContentEnglish": true,
    "relativePath": "src/content/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/index.md",
    "intl": {
        "language": "lt",
        "defaultLanguage": "en",
        "languages": [
            "en",
            "ar",
            "bn",
            "cs",
            "de",
            "el",
            "es",
            "fa",
            "fi",
            "fr",
            "hi",
            "hu",
            "id",
            "ig",
            "it",
            "ja",
            "ko",
            "lt",
            "ml",
            "nl",
            "nb",
            "pl",
            "pt",
            "pt-br",
            "ro",
            "ru",
            "se",
            "sk",
            "sl",
            "tr",
            "uk",
            "vi",
            "zh",
            "zh-tw"
        ],
        "messages": {
            "about-ethereum-org": "Apie ethereum.org",
            "about-us": "Apie mus",
            "brand-assets": "Prekės ženklo turtas",
            "community": "Bendruomenė",
            "contact": "Susisiekti",
            "contributing": "Prisidėkite",
            "cookie-policy": "Slapukų naudojimo politika",
            "decentralized-applications-dapps": "Decentralizuotos programėlės (dapps'ai)",
            "developer-resources": "Ištekliai kūrėjams",
            "developers": "Kūrėjams",
            "developers-home": "Kūrėjų pagrindinis puslapis",
            "documentation": "Dokumentacija",
            "ef-blog": "Ethereum fondo tinklaraštis",
            "eips": "Pasiūlymai, kaip tobulinti Ethereum",
            "enterprise": "Verslui",
            "ethereum": "Ethereum",
            "ethereum-2-0": "Ethereum 2.0",
            "ethereum-brand-assets": "Ethereum prekės ženklo turtas",
            "ethereum-community": "Ethereum bendruomenė",
            ...hundreds of more lines...
        },
        "routed": true,
        "originalPath": "/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/",
        "redirect": false
    }
}
```

For whatever reason, the logs print out the entire page context, which is >1K lines due to all the intl messages in the page context object.

**Describe the solution you'd like**

- Ideally we identify the root cause - why are these queries taking "too long"?
- At the least, we should silence these logs so it doesn't cripple our ability to investigate build failures

**Describe alternatives you've considered**

**Additional context**

May be related to #2802, might be worth investigating how to optimize build times.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by samajammin** [comment] 2021-04-08 21:44
This looks like it may be related to our v3 migration (#2780) - see this open issue: https://github.com/gatsbyjs/gatsby/issues/30256

**Comment by samajammin** [comment] 2021-04-08 21:48
At least for now, silencing the logs doesn't appear to be possible. Here's where this is logged in Gatsby: https://github.com/gatsbyjs/gatsby/blob/54d4721462b9303fed723fdcb15ac5d72e103778/packages/gatsby/src/query/query-runner.ts#L30

**Comment by samajammin** [comment] 2021-04-08 22:02
Opened a discussion in Gatsby here: https://github.com/gatsbyjs/gatsby/discussions/30767

**Comment by cdomashn** [comment] 2021-12-19 18:43
Let me take a look at the logs/settings, etc.

**Comment by cdomashn** [comment] 2021-12-24 00:11
1. Gatsby does not seem to offer many startup options one can experiment with (to put it mildly).
2. The issue of overly verbose startup Gatsby logs is not uncommon. As a remedy, one of the websites suggests running
- the localized/translated website/portal, and
- the primary english-only website/portal
separately.

Doing so might be a good option for other reasons actually; and the benefits may outweigh the disadvantages.

**Comment by minimalsm** [comment] 2022-01-31 11:52
Thanks @cdomashn 

[Had a look at the logs](https://www.gatsbyjs.com/dashboard/5e02f963-3fe5-4e37-a1e7-ac05f7753a86/sites/354db32e-7775-49f1-b099-b42a9bfcf83a/builds/a7a005b5-7eaf-4639-9b3a-41010c623331/details#rawLogs). Since the move to Gatsby V4/Gatsby Cloud this doesn't seem to be the same issue. Can we close this?

**Comment by minimalsm** [comment] 2022-01-31 17:42
We suspect this is still happening locally but not on Gatsby cloud logs

**Comment by wackerow** [comment] 2022-02-09 00:15
This has not been reproducible since migration to Gatsby Cloud / Gatsby v4. Can reopen if needed but closing for now.

**Closed by wackerow** 2022-02-09 00:15 UTC
Labels: needs grooming
