### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sarthak-kumar-shailendra** [ethereum/ethereum-org-website#11221] opened 2023-09-20 17:23 UTC
### Describe the bug

Description - The Twitter logo has been updated recently and hasn't been updated on ethereum site.

### To reproduce

1. Go to footer section and see twitter old lcon
<img width="201" alt="Screenshot 2023-09-20 at 10 45 31 PM" src="https://github.com/ethereum/ethereum-org-website/assets/69191344/51b7b63d-73af-4521-bb66-7a27ecea7bc8">

or
1. Go to find wallet page 
<img width="316" alt="Screenshot 2023-09-20 at 10 45 43 PM" src="https://github.com/ethereum/ethereum-org-website/assets/69191344/327278c4-3d05-4855-bdd4-e1e26f9f1fe6">

or 

1. Go to quiz hub page
<img width="615" alt="Screenshot 2023-09-20 at 10 46 40 PM" src="https://github.com/ethereum/ethereum-org-website/assets/69191344/1ff3aa8b-da83-4c00-955b-2d2d298ec153">

2. Also, after completing the quiz 
<img width="432" alt="Screenshot 2023-09-20 at 10 47 08 PM" src="https://github.com/ethereum/ethereum-org-website/assets/69191344/a9dc4785-9d5f-447a-996c-12bb67a79b24">

### Expected behavior

The Twitter logo should be changed to X.

<img width="213" alt="Screenshot 2023-09-20 at 10 51 31 PM" src="https://github.com/ethereum/ethereum-org-website/assets/69191344/5c8f5e6c-89ad-477b-8295-bd63c0081938">

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by corwintines** [comment] 2023-09-20 19:04
Duplicate of https://github.com/ethereum/ethereum-org-website/issues/10797

**Closed by corwintines** 2023-09-20 19:04 UTC
Labels: bug :bug:, needs-triage
