### ISSUE TITLE
Tasks on ../about/#roadmap aren't loading.

### ISSUE THREAD

**Issue by eenti** [ethereum/ethereum-org-website#9409] opened 2023-02-06 16:53 UTC
### Describe the bug

Seems like the tasks that are supposed to show up on the Roadmap section of the About page aren't loading.

### To reproduce

1. Go to https://ethereum.org/en/about
2. Scroll down to the roadmap section
4. See error on Work in progress, Planned features and Implemented features

### Expected behavior

I don't recall seeing it work, but I assume it's supposed to show and link to tasks/epics

### Screenshots

<img width="805" alt="Screenshot 2023-02-06 at 12 51 11" src="https://user-images.githubusercontent.com/76917690/217033532-0906c055-bab8-4fcd-8665-192cdd8160f7.png">

### Desktop (please complete the following information)

- OS: macOS Ventura 13.0
- Browser: Brave
- Version 1.47.186 Chromium: 109.0.5414.119

**Comment by MrJithil** [comment] 2023-02-08 11:47
Investigated this issue, and found that `GITHUB_TOKEN` seems invalid. 

Locally, tested with the personal token and data loading perfectly. 

CC: @corwintines @samajammin @ethereum/core-dev

**Comment by samajammin** [comment] 2023-02-08 14:33
Hey! Thanks for reporting & investigating but this is a duplicate of #9158 & is solved in https://github.com/ethereum/ethereum-org-website/pull/9358

**Comment by samajammin** [comment] 2023-02-09 00:10
Closing this out in favor of https://github.com/ethereum/ethereum-org-website/issues/9158

**Closed by samajammin** 2023-02-09 00:10 UTC
Labels: bug :bug:
