### ISSUE TITLE
nft page is broken for longer languages due to the button

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#6268] opened 2022-05-09 12:36 UTC
**Describe the bug**

The structure of the site is broken on mobile in some languages. Affected languages are turkish,  german and probably some others too.

The reason is too large text in the button.

**To Reproduce**
1. open the page https://ethereum.org/de/nft/  on mobile (tested on iPhone 8)
2. see the navigation button at the bottom of the page

**Expected behavior**
the text is cut to two rows

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Screenshots**
![IMG_5390](https://user-images.githubusercontent.com/100724231/167409937-ea4c73c3-75fd-4695-bc08-54e173a48dd2.PNG)
![IMG_5391](https://user-images.githubusercontent.com/100724231/167409946-389c52c2-de86-43d1-8b9f-6ae99133c014.PNG)
![IMG_5393](https://user-images.githubusercontent.com/100724231/167409952-56aa9b37-4e75-4471-aaa3-8a6bef933931.PNG)

**Comment by avcdsld** [comment] 2022-05-29 13:11
Hi. I can work on this.

**Comment by avcdsld** [comment] 2022-05-29 13:36
> The reason is too large text in the button.

I found that the cause was not a button, but a table that contained long words that could not be broken (e.g. `Wiederverkaufsgebühren`). The whole layout is fixed by adding a hyphenation CSS setting.

<img width="385" alt="ScreenShot 2022-05-29 22 25 54" src="https://user-images.githubusercontent.com/10495516/170871578-80d519fa-01a3-413c-973c-ef23397957d7.png">

**Closed** 2022-05-30 10:53 UTC
Labels: bug :bug:
